"""empty message

Revision ID: bf19da6e3baf
Revises: 
Create Date: 2021-08-03 06:25:36.035587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf19da6e3baf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('board_number', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('board_comment', sa.String(length=200), nullable=False),
    sa.Column('board_restaurant', sa.String(length=20), nullable=False),
    sa.Column('board_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], ),
    sa.PrimaryKeyConstraint('board_number')
    )
    op.drop_column('member', 'member_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('member_date', mysql.DATETIME(), nullable=False))
    op.drop_table('board')
    # ### end Alembic commands ###
